trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    version: '7.x'
    performMultiLevelLookup: true

- script: dotnet workload restore src/EventLogExpert.sln
  displayName: 'dotnet workload restore'

- script: dotnet test src/EventLogExpert.sln
  displayName: 'dotnet test'

- script: dotnet publish src/EventLogExpert.EventDbTool/EventLogExpert.EventDbTool.csproj -c Release --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesForSelfExtract=true -o dist
  displayName: 'dotnet publish EventDbTool'

- script: dotnet publish src/EventLogExpert/EventLogExpert.csproj -f net6.0-windows10.0.19041.0 -c Release /p:RuntimeIdentifierOverride=win10-x64
  displayName: 'dotnet publish EventLogExpert'

- pwsh: |
    Get-ChildItem src\EventLogExpert\bin\Release\EventLogExpert*.msix -Recurse | % { Copy-Item $_ dist }
  displayName: 'copy msix to dist'

- pwsh: |
    dir dist
  displayName: 'show binaries'
