// // Copyright (c) Microsoft Corporation.
// // Licensed under the MIT License.

using System.Text.RegularExpressions;

namespace EventLogExpert.UI.Services;

/// <summary>
/// Normalizes a GitHub release body into a clean Markdown document that can be
/// rendered by <see cref="ReleaseNotesMarkdownRenderer"/>.
///
/// Future releases are hand-authored in rich Markdown (headings, bold, lists,
/// links). Hand-authored content largely passes through; the only rewrites
/// applied universally are converting <c>*</c> bullet markers to <c>-</c> for
/// consistency and collapsing runs of 3+ blank lines. Legacy releases used a
/// flat list of <c>* &lt;commit-id&gt; description</c> bullets, sometimes
/// wrapped in raw HTML (<c>&lt;details&gt;</c>/<c>&lt;summary&gt;</c>/
/// <c>&lt;b&gt;</c>) and followed by an auto-generated build-pipeline footer.
/// This normalizer strips that noise so the renderer (which escapes raw HTML)
/// does not surface the markup as literal text.
/// </summary>
public static partial class ReleaseNotesNormalizer
{
    public static string Normalize(string? rawBody)
    {
        if (string.IsNullOrWhiteSpace(rawBody))
        {
            return string.Empty;
        }

        var working = rawBody.Replace("\r\n", "\n").Replace('\r', '\n');

        working = SummaryTagRegex().Replace(working, match =>
        {
            // Strip any nested HTML tags (legacy or otherwise) so they do not
            // surface as literal text inside the promoted heading.
            var inner = AnyHtmlTagRegex().Replace(match.Groups[1].Value, string.Empty).Trim();
            return string.IsNullOrEmpty(inner) ? string.Empty : $"\n\n## {inner}\n";
        });

        working = LegacyHtmlTagRegex().Replace(working, string.Empty);
        working = AutoGeneratedFooterRegex().Replace(working, string.Empty);
        working = BulletRegex().Replace(working, match => $"- {match.Groups[1].Value.Trim()}");
        working = CollapseBlankLinesRegex().Replace(working, "\n\n");

        return working.Trim();
    }

    [GeneratedRegex(@"<[^>]+>")]
    private static partial Regex AnyHtmlTagRegex();

    [GeneratedRegex(@"^This list of changes was \[auto generated\][^\n]*$", RegexOptions.Multiline)]
    private static partial Regex AutoGeneratedFooterRegex();

    /// <summary>
    /// Matches a <c>* </c> bullet whose content optionally begins with a commit
    /// identifier — either a 40-character SHA or a Markdown link
    /// (e.g. <c>[abc1234](https://...)</c>) — and rewrites it as a clean
    /// <c>- description</c> bullet. Bullets without a commit prefix are simply
    /// converted from <c>*</c> to <c>-</c> style for consistency.
    /// </summary>
    [GeneratedRegex(@"^\*\s+(?:\[[0-9a-f]{6,}\]\([^)\s]+\)\s+|[0-9a-f]{40}\s+)?(.+)$",
        RegexOptions.Multiline | RegexOptions.IgnoreCase)]
    private static partial Regex BulletRegex();

    [GeneratedRegex(@"\n{3,}")]
    private static partial Regex CollapseBlankLinesRegex();

    /// <summary>
    /// Strips the structural HTML wrappers and inline emphasis tags that
    /// historically appeared in GitHub release bodies. Inner text is preserved.
    /// </summary>
    [GeneratedRegex(@"</?(?:details|summary|b|i|em|strong)[^>]*>", RegexOptions.IgnoreCase)]
    private static partial Regex LegacyHtmlTagRegex();

    /// <summary>
    /// Captures a <c>&lt;summary&gt;</c> block and promotes its inner text to a
    /// section heading so the collapsible "See More" label is preserved as a
    /// visible divider in the rendered notes. Any nested HTML tags inside the
    /// captured text are removed by <see cref="AnyHtmlTagRegex"/> before the
    /// heading is emitted, so even non-legacy markup (e.g. <c>&lt;iframe&gt;</c>)
    /// cannot surface as literal text in the heading.
    /// </summary>
    [GeneratedRegex(@"<summary[^>]*>(.*?)</summary>", RegexOptions.IgnoreCase | RegexOptions.Singleline)]
    private static partial Regex SummaryTagRegex();
}


